# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/go/bin:$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=14

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting zsh-autosuggestions pip gitfast)

source $ZSH/oh-my-zsh.sh

# User configuration
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=9,bold
ZSH_HIGHLIGHT_STYLES[reserved-words]=fg=5
ZSH_HIGHLIGHT_STYLES[alias]=fg=6
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=6,underline
ZSH_HIGHLIGHT_STYLES[global-alias]=fg=6
ZSH_HIGHLIGHT_STYLES[builtin]=fg=6
ZSH_HIGHLIGHT_STYLES[function]=fg=6
ZSH_HIGHLIGHT_STYLES[command]=fg=15
ZSH_HIGHLIGHT_STYLES[precommand]=fg=6,underline
ZSH_HIGHLIGHT_STYLES[command-separator]=fg=7
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=15
ZSH_HIGHLIGHT_STYLES[autodirectory]=fg=6,underline
ZSH_HIGHLIGHT_STYLES[path]=fg=15,underline
ZSH_HIGHLIGHT_STYLES[globbing]=fg=3,underline
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=6
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]=fg=7
ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]=fg=3
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=10
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=10
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=10
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=3
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=3
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=3
ZSH_HIGHLIGHT_STYLES[assign]=fg=5
ZSH_HIGHLIGHT_STYLES[redirection]=fg=5
ZSH_HIGHLIGHT_STYLES[comment]=fg=7
ZSH_HIGHLIGHT_STYLES[named-fd]=fg=5
ZSH_HIGHLIGHT_STYLES[numeric-fd]=fg=5
ZSH_HIGHLIGHT_STYLES[arg0]=fg=6
ZSH_HIGHLIGHT_STYLES[default]=fg=15


export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_GB.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='code'
else
  export EDITOR='mvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Edit this config
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"

# LS
alias ls='lsd'
alias ll='ls -la'
alias lt='ls --tree'

# Change the current virtualenv
alias venv='source venv'

# History
alias h='history'
alias hg='history | grep'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Enable TheFuck to retry failed/incorrect commands
eval $(thefuck --alias)

# Load user specific scripts
source ~/.profile.d/01_ssh_agent
